language: ruby
rvm:
 - 2.3.1
services:
  - redis-server
  - postgresql
before_script:  
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database courser_test;' -U postgres
  - sleep 5
script:
  - bundle exec rspec spec/controllers/*.rb
  - bundle exec rspec spec/models/*.rb

