language: ruby
rvm:
 - 2.3.1
services:
  - redis-server
  - postgresql
before_script:
  - psql -c 'create database courser_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: xvfb-run bundle exec rspec