default: &default
  adapter: postgresql
  user: root
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: courser_dev
test:
  <<: *default
  database: courser_test

production:
  <<: *default
  database: courser_production
